# Generated by Django 4.1.2 on 2022-10-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='apodo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ciudad',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_equipo',
            field=models.IntegerField(default=0),
        ),
    ]
